---

ip: "192.168.99.99"
provider: virtualbox
name: devboxes
hostname: localhost
box: ubuntu/trusty64
memory: 2096
cpus: 1
script_file: nginx/scripts.sh
ssh_username: vagrant
ssh_password: vagrant
default_ports: true

folders:
    - map: ../
      to: /var/www
      other: true

sites:
    - map: new-server.local
      to: /var/www/
      type: nginx
      php: 5


# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
